server:
  port: 8087

jwt:
  secret: your-256-bit-secret-key-change-in-production-env

manager:
  secret:
    key: super-secret-manager-key-2024

services:
  client:
    url: http://client-service:8085
  account:
    url: http://account-service:8086
  atm:
    url: http://atm-service:8081
  branch:
    url: http://branch-service:8082
  order:
    url: http://order-service:8083
  card:
    url: http://card-service:8084

logging:
  level:
    com.bank.gateway: DEBUG